#!/usr/bin/env python3
"""Update AI-related Surge rule lists from official sources."""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from html import unescape
from pathlib import Path
from typing import Iterable
from urllib.error import URLError
from urllib.request import Request, urlopen

OUTPUT_PATH = Path("AI.list")

HOSTNAME_RE = re.compile(r"\b(?:[a-z0-9-]+\.)+[a-z]{2,}\b", re.IGNORECASE)
LIST_ITEM_RE = re.compile(
    r"<li[^>]*>.*?<code[^>]*>(?P<domain>[a-z0-9.-]+\.[a-z]{2,})</code>"
    r"(?P<rest>.*?)</li>",
    re.IGNORECASE | re.DOTALL,
)


@dataclass(frozen=True)
class Provider:
    name: str
    source_url: str
    intro_markers: tuple[str, ...]
    fallback_domains: tuple[str, ...]


CLAUDE_CODE = Provider(
    name="Claude Code",
    source_url="https://code.claude.com/docs/en/network-config",
    intro_markers=(
        "Claude Code requires access to the following URLs:",
        "The native installer and update checks also require the following URLs.",
    ),
    fallback_domains=(
        "api.anthropic.com",
        "claude.ai",
        "downloads.claude.ai",
        "platform.claude.com",
        "storage.googleapis.com",
    ),
)

PROVIDERS = (CLAUDE_CODE,)


def fetch_html(url: str) -> str:
    request = Request(
        url,
        headers={
            "User-Agent": (
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/123.0.0.0 Safari/537.36"
            )
        },
    )
    with urlopen(request, timeout=15) as response:
        return response.read().decode("utf-8", errors="replace")


def sanitize_text(text: str) -> str:
    without_tags = re.sub(r"<[^>]+>", " ", text)
    return re.sub(r"\s+", " ", unescape(without_tags)).strip()


def looks_relevant(domain: str) -> bool:
    domain = domain.lower()
    if domain == "storage.googleapis.com":
        return True
    roots = ("anthropic.com", "claude.ai", "claude.com")
    return any(domain == root or domain.endswith(f".{root}") for root in roots)


def extract_lists_by_intro(html_text: str, markers: Iterable[str]) -> list[str]:
    fragments: list[str] = []
    for marker in markers:
        position = html_text.find(marker)
        if position == -1:
            continue
        match = re.search(r"<ul[^>]*>.*?</ul>", html_text[position:], re.IGNORECASE | re.DOTALL)
        if match:
            fragments.append(match.group(0))
    return fragments


def extract_domains(provider: Provider, html_text: str) -> list[str]:
    domains: set[str] = set()
    for fragment in extract_lists_by_intro(html_text, provider.intro_markers):
        for match in LIST_ITEM_RE.finditer(fragment):
            domain = match.group("domain").lower()
            if looks_relevant(domain):
                domains.add(domain)

    if domains:
        return sorted(domains)

    for domain in HOSTNAME_RE.findall(sanitize_text(html_text)):
        domain = domain.lower()
        if looks_relevant(domain):
            domains.add(domain)
    return sorted(domains)


def resolve_provider_domains(provider: Provider) -> list[str]:
    try:
        html_text = fetch_html(provider.source_url)
    except URLError as exc:
        print(
            f"[warn] {provider.name}: failed to fetch official source, using fallback ({exc})",
            file=sys.stderr,
        )
        return sorted(set(provider.fallback_domains))

    domains = extract_domains(provider, html_text)
    if domains:
        return domains

    print(
        f"[warn] {provider.name}: failed to parse official source, using fallback",
        file=sys.stderr,
    )
    return sorted(set(provider.fallback_domains))


def render_rules() -> str:
    lines = [
        "# Auto-generated by scripts/update_ai_rules.py.",
        "# Intended for Surge RULE-SET usage.",
        "",
    ]

    for provider in PROVIDERS:
        domains = resolve_provider_domains(provider)
        lines.append(f"# {provider.name}")
        lines.append(f"# Source: {provider.source_url}")
        for domain in domains:
            lines.append(f"DOMAIN,{domain}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    OUTPUT_PATH.write_text(render_rules(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
